name: "Draw Keymap"

on:
  workflow_dispatch:
  # push時に自動で実行する場合は、以下のコメントアウトを外す
  # push:
  #   paths:
  #     - "config/soa44.keymap"
  #     - "keymap_drawer.config.yaml"
  #     - "boards/shields/soa44/soa44.dtsi"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@f9cf9d3677368a7fb1dc505c51b8156fafa66fe2
    permissions:
      contents: write
    with:
      commit_message: "${{ github.event.head_commit.message || 'Update keymap drawing' }}"
      amend_commit: false
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "keymap-drawer"
      destination: "both"